router_settings:
  routing_strategy: usage-based-routing-v2
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  redis_password: os.environ/REDIS_PASSWORD
  enable_pre_call_check: true
environment_variables:
  STORE_MODEL_IN_DB: 'True'
  LITELLM_LOG: INFO
litellm_settings:
  cache: true
  cache_params:
    type: redis
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT
    password: os.environ/REDIS_PASSWORD
  max_budget: 1000000000.0
  budget_duration: 1mo
  max_internal_user_budget: 1000000000.0
  internal_user_budget_duration: 1mo
  success_callback:
  - s3
  failure_callback:
  - s3
  service_callback:
  - s3
  s3_callback_params:
    s3_bucket_name: null
    s3_region_name: null
